name: furry_diary
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.4.9
  dio: ^5.3.3
  in_app_purchase: ^3.2.0
  json_annotation: ^4.8.1
  flutter_local_notifications: 17.2.4
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  image_picker: ^1.1.2
  flutter_animate: ^4.5.2
  uuid: ^4.5.3
  flutter_slidable: ^4.0.3
  path_provider: ^2.1.5
  file_picker: ^8.1.2
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
